In [4]:
import torch
import torch.nn as nn
import torchvision
import distiller.quantization as quantization

In [3]:
dir(quantization)

['ClipMode',
 'ClippedLinearQuantization',
 'DorefaQuantizer',
 'LinearQuantMode',
 'LinearQuantizeSTE',
 'PACTQuantizer',
 'PostTrainLinearQuantizer',
 'QuantAwareTrainRangeLinearQuantizer',
 'Quantizer',
 'RangeLinearQuantConcatWrapper',
 'RangeLinearQuantEltwiseAddWrapper',
 'RangeLinearQuantEltwiseMultWrapper',
 'RangeLinearQuantParamLayerWrapper',
 'RangeLinearQuantWrapper',
 'WRPNQuantizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'add_post_train_quant_args',
 'q_utils']

In [25]:
data = torch.rand(1, 3, 224, 224)
model = torchvision.models.alexnet(pretrained=True)
model = model.eval()

# origin

In [26]:
out = model(data)

In [27]:
print(out)

tensor([[-1.9220e+00, -1.3319e-01,  1.4732e-01,  1.7044e+00,  1.3934e+00,
         -1.0764e-01,  1.2395e+00, -4.6053e-01, -1.5235e+00, -1.3143e+00,
         -2.2875e-02,  9.6593e-01,  7.4954e-02,  9.0510e-01,  1.0342e+00,
         -1.0313e-01,  9.4448e-01, -5.9188e-01,  8.6463e-01,  8.3757e-01,
         -4.2465e-01,  8.5829e-01,  2.7373e-01,  1.7030e-01,  1.1365e+00,
         -3.3187e-01, -1.3605e+00, -4.7181e-01,  9.1623e-02, -3.5834e-01,
         -1.3436e+00,  1.6000e-01, -1.7269e+00,  7.6840e-01,  1.4935e+00,
         -1.5220e+00,  1.6906e-01,  3.4379e-01, -2.2537e-01, -1.0025e+00,
          7.7540e-01, -8.7769e-01, -6.3358e-01,  5.1651e-01, -1.2370e-01,
         -1.2794e-01,  9.7674e-01, -1.7655e+00, -6.5739e-01, -7.8677e-01,
          1.3729e+00, -2.4004e+00, -3.2809e-01, -2.8855e-01,  1.3058e-01,
         -7.7715e-01, -1.1926e+00, -9.3408e-01,  7.6217e-01, -1.4898e-01,
          1.2258e-01, -3.5594e-01, -5.6514e-01, -5.2621e-01,  3.1584e-01,
          7.3709e-01, -7.3343e-01,  1.

In [28]:
for n, p in model.named_parameters():
    print(n, p)
    break

features.0.weight Parameter containing:
tensor([[[[ 1.1864e-01,  9.4069e-02,  9.5435e-02,  ...,  5.5822e-02,
            2.1575e-02,  4.9963e-02],
          [ 7.4882e-02,  3.8940e-02,  5.2979e-02,  ...,  2.5709e-02,
           -1.1299e-02,  4.1590e-03],
          [ 7.5425e-02,  3.8779e-02,  5.4930e-02,  ...,  4.3596e-02,
            1.0225e-02,  1.3251e-02],
          ...,
          [ 9.3155e-02,  1.0374e-01,  6.7547e-02,  ..., -2.0277e-01,
           -1.2839e-01, -1.1220e-01],
          [ 4.3544e-02,  6.4916e-02,  3.6164e-02,  ..., -2.0248e-01,
           -1.1376e-01, -1.0719e-01],
          [ 4.7369e-02,  6.2543e-02,  2.4758e-02,  ..., -1.1844e-01,
           -9.5567e-02, -8.3890e-02]],

         [[-7.2634e-02, -5.7996e-02, -8.0661e-02,  ..., -6.0304e-04,
           -2.5309e-02,  2.5471e-02],
          [-6.9042e-02, -6.7562e-02, -7.6367e-02,  ..., -3.9616e-03,
           -3.0402e-02,  1.0477e-02],
          [-9.9517e-02, -8.5592e-02, -1.0521e-01,  ..., -2.6587e-02,
           -2.2777

# quant 

In [35]:
quantizer = quantization.PostTrainLinearQuantizer(model)
quantizer.prepare_model()

In [34]:
out = model(data)

AttributeError: 'RangeLinearQuantParamLayerWrapper' object has no attribute 'bias'

In [ ]:
print(out)

In [11]:
for n, p in model.named_parameters():
    print(n, p)
    break

features.0.wrapped_module.weight Parameter containing:
tensor([[[[ 16.,  13.,  13.,  ...,   8.,   3.,   7.],
          [ 10.,   5.,   7.,  ...,   3.,  -2.,   1.],
          [ 10.,   5.,   7.,  ...,   6.,   1.,   2.],
          ...,
          [ 13.,  14.,   9.,  ..., -28., -17., -15.],
          [  6.,   9.,   5.,  ..., -27., -15., -15.],
          [  6.,   8.,   3.,  ..., -16., -13., -11.]],

         [[-10.,  -8., -11.,  ...,  -0.,  -3.,   3.],
          [ -9.,  -9., -10.,  ...,  -1.,  -4.,   1.],
          [-14., -12., -14.,  ...,  -4.,  -3.,   1.],
          ...,
          [-21., -12., -13.,  ...,  42.,  25.,  11.],
          [-19., -10., -10.,  ...,  28.,  22.,  13.],
          [-12.,  -5.,  -7.,  ...,  22.,  20.,  14.]],

         [[ -3.,  -0.,  -4.,  ...,   5.,  -1.,   4.],
          [  0.,   3.,   1.,  ...,   3.,  -2.,   2.],
          [  1.,   4.,   0.,  ...,   2.,  -0.,   1.],
          ...,
          [ -9.,  -2.,  -8.,  ...,  14.,  -1., -11.],
          [ -6.,   0.,  -5.,  ..